name: pnpm lint-format
on:
  push:
    branches: [ "develop", "main", "feature/*" ]
  pull_request:
    branches: [ "develop", "main", "feature/*" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install

      - run: pnpm run --if-present test --passWithNoTests
      - run: pnpm run --if-present lint
      - run: pnpm run --if-present format
